# -*- coding: utf-8 -*-
"""InstagramUser.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B6g3A4U-L9IF49s50ZKou2-33pNTyaRb
"""

import pandas as pd
import csv

insta_url = 'https://www.instagram.com/'

df = pd.read_csv('UserInfo.csv')
users = df['userName'].tolist()
insta = df['userInsta'].tolist()

from posixpath import split
file = open("UserInfo.csv", "r")
d = {}
for line in file:
  split = line.strip().split(",")
  d[split[0]] = split[1]

if True:
    nome = input('Digite seu nome: ')
    if nome in users:
      print(f'Olá, {nome}. Acesse seu perfil do Instagram através do link abaixo: \n {instaurl}/{d[nome]}')
    else:
      print('Sinto muito, seu nome não se encontra no banco de dados.')